@startuml diagrama-de-classe

abstract class Espaco {
    - Int capacidade
    - Double preco
    - String descricao

    + Int getCapacidade()
    + Double getPreco()
    + String getDescricao()
    + String setCapacidade()
    + Double setPreco()
    + String setDescricao()
}

class Reserva {
    - Espaco espaco
    - Date dataInicial
    - Date dataFinal
    - Boolean reservado

    + Espaco getEspaco()
    + Date getDataInicial()
    + Date getDataFinal()
    + Boolean getReservado()

    + void reservarEspaco()
    + void cancelarReserva()
    + void verReserva()


}

interface Pagamento {

}

class PagamentoCartao {

}

class PagamentoDinheiro {

}

interface Usuario {
    - nome
    - email
    - senha


}

class Cliente {

}

class Admin {

    # void cancelarReserva()

}


Reserva *-- Espaco
Pagamento <|.. PagamentoCartao
Pagamento <|.. PagamentoDinheiro

Usuario <|.. Cliente
Usuario <|.. Admin

Reserva "0..*".."1" Cliente

Cliente .. Pagamento