@startuml sequencia-reserva-segura
actor Cliente
participant "ReservaController" as Ctrl
participant "ReservaService" as Svc
participant "ReservaRepository" as Repo
database "Banco Centralizado" as DB
participant "PagamentoService" as Pag

Cliente -> Ctrl: Solicitar Reserva(espaço X, data Y)
Ctrl -> Svc: criarReserva()

group Transação
    Svc -> Repo: iniciarTransacao()

    note right of DB
        O "SELECT FOR UPDATE" trava
        o registro do espaço no Banco
        até o fim da transação.
        Isso impede Double-Booking.
    end note
    Svc -> Repo: verificarDisponibilidadeLock(Espaço X, Data Y)
    Repo -> DB: SELECT ... FOR UPDATE

    alt Espaço Ocupado
        Repo --> Svc: Ocupado
        Svc --> Cliente: Erro: Espaço já reservado
    else Espaço Livre
        Svc -> Pag: processarPagamento()
        activate Pag
        Pag --> Svc: Pagamento OK
        deactivate Pag

        Svc -> Repo: salvarReserva()
        Repo -> DB: INSERT INTO Reservas...
        Svc -> Repo: commitTransacao()
        Svc --> Cliente: Reserva Confirmada!
    end
end
@enduml